# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:58:52+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    BrlcsCertificatePostRequest,
    BrlcsCertificatePostResponse,
    BrlcsCertificatePostResponse1,
    BrlcsCertificatePostResponse2,
    BrlcsCertificatePostResponse3,
    BrlcsCertificatePostResponse4,
    BrlcsCertificatePostResponse5,
    BrlcsCertificatePostResponse6,
    DpcerCertificatePostRequest,
    DpcerCertificatePostResponse,
    DpcerCertificatePostResponse1,
    DpcerCertificatePostResponse2,
    DpcerCertificatePostResponse3,
    DpcerCertificatePostResponse4,
    DpcerCertificatePostResponse5,
    DpcerCertificatePostResponse6,
    FmcerCertificatePostRequest,
    FmcerCertificatePostResponse,
    FmcerCertificatePostResponse1,
    FmcerCertificatePostResponse2,
    FmcerCertificatePostResponse3,
    FmcerCertificatePostResponse4,
    FmcerCertificatePostResponse5,
    FmcerCertificatePostResponse6,
    IncerCertificatePostRequest,
    IncerCertificatePostResponse,
    IncerCertificatePostResponse1,
    IncerCertificatePostResponse2,
    IncerCertificatePostResponse3,
    IncerCertificatePostResponse4,
    IncerCertificatePostResponse5,
    IncerCertificatePostResponse6,
    LccepCertificatePostRequest,
    LccepCertificatePostResponse,
    LccepCertificatePostResponse1,
    LccepCertificatePostResponse2,
    LccepCertificatePostResponse3,
    LccepCertificatePostResponse4,
    LccepCertificatePostResponse5,
    LccepCertificatePostResponse6,
    NdcerCertificatePostRequest,
    NdcerCertificatePostResponse,
    NdcerCertificatePostResponse1,
    NdcerCertificatePostResponse2,
    NdcerCertificatePostResponse3,
    NdcerCertificatePostResponse4,
    NdcerCertificatePostResponse5,
    NdcerCertificatePostResponse6,
    ObcerCertificatePostRequest,
    ObcerCertificatePostResponse,
    ObcerCertificatePostResponse1,
    ObcerCertificatePostResponse2,
    ObcerCertificatePostResponse3,
    ObcerCertificatePostResponse4,
    ObcerCertificatePostResponse5,
    ObcerCertificatePostResponse6,
    RmcerCertificatePostRequest,
    RmcerCertificatePostResponse,
    RmcerCertificatePostResponse1,
    RmcerCertificatePostResponse2,
    RmcerCertificatePostResponse3,
    RmcerCertificatePostResponse4,
    RmcerCertificatePostResponse5,
    RmcerCertificatePostResponse6,
    RscerCertificatePostRequest,
    RscerCertificatePostResponse,
    RscerCertificatePostResponse1,
    RscerCertificatePostResponse2,
    RscerCertificatePostResponse3,
    RscerCertificatePostResponse4,
    RscerCertificatePostResponse5,
    RscerCertificatePostResponse6,
    RucerCertificatePostRequest,
    RucerCertificatePostResponse,
    RucerCertificatePostResponse1,
    RucerCertificatePostResponse2,
    RucerCertificatePostResponse3,
    RucerCertificatePostResponse4,
    RucerCertificatePostResponse5,
    RucerCertificatePostResponse6,
    SicrdCertificatePostRequest,
    SicrdCertificatePostResponse,
    SicrdCertificatePostResponse1,
    SicrdCertificatePostResponse2,
    SicrdCertificatePostResponse3,
    SicrdCertificatePostResponse4,
    SicrdCertificatePostResponse5,
    SicrdCertificatePostResponse6,
    VlcerCertificatePostRequest,
    VlcerCertificatePostResponse,
    VlcerCertificatePostResponse1,
    VlcerCertificatePostResponse2,
    VlcerCertificatePostResponse3,
    VlcerCertificatePostResponse4,
    VlcerCertificatePostResponse5,
    VlcerCertificatePostResponse6,
)

app = MCPProxy(
    description="eDistrict Andaman (https://edistrict.andaman.gov.in/) is the online service delivery portal for Andaman & Nicobar Islands. Certain documents issued by it (e.g. Local Certificate,Income Certificate,OBC Certificate,Resident Certificate  etc) can be pulled into citizens' DigiLocker accounts.",
    termsOfService='https://apisetu.gov.in/terms.php',
    title='eDistrict Andaman & Nicobar Islands, Andaman & Nicobar',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/edistrictandaman/v3'}],
)


@app.post(
    '/brlcs/certificate',
    description=""" API to verify Bar License. """,
    tags=['certificate_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def brlcs(body: BrlcsCertificatePostRequest = None):
    """
    Bar License
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/dpcer/certificate',
    description=""" API to verify Dependency Certificate. """,
    tags=['certificate_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def dpcer(body: DpcerCertificatePostRequest = None):
    """
    Dependency Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/fmcer/certificate',
    description=""" API to verify Family Membership Certificate. """,
    tags=['certificate_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def fmcer(body: FmcerCertificatePostRequest = None):
    """
    Family Membership Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/incer/certificate',
    description=""" API to verify Income Certificate. """,
    tags=['certificate_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def incer(body: IncerCertificatePostRequest = None):
    """
    Income Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/lccep/certificate',
    description=""" API to verify Local Candidate/ Status Certificate. """,
    tags=['certificate_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def lccep(body: LccepCertificatePostRequest = None):
    """
    Local Candidate/ Status Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ndcer/certificate',
    description=""" API to verify No Dues/ Objection Certificate. """,
    tags=['certificate_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def ndcer(body: NdcerCertificatePostRequest = None):
    """
    No Dues/ Objection Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/obcer/certificate',
    description=""" API to verify OBC Certificate. """,
    tags=['certificate_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def obcer(body: ObcerCertificatePostRequest = None):
    """
    OBC Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/rmcer/certificate',
    description=""" API to verify Marriage Certificate. """,
    tags=['certificate_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def rmcer(body: RmcerCertificatePostRequest = None):
    """
    Marriage Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/rscer/certificate',
    description=""" API to verify Residence Certificate. """,
    tags=['certificate_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def rscer(body: RscerCertificatePostRequest = None):
    """
    Residence Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/rucer/certificate',
    description=""" API to verify Regional Language(s) Certificate. """,
    tags=['certificate_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def rucer(body: RucerCertificatePostRequest = None):
    """
    Regional Language(s) Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sicrd/certificate',
    description=""" API to verify Senior Citizen Identity Card/ Certificate. """,
    tags=['certificate_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def sicrd(body: SicrdCertificatePostRequest = None):
    """
    Senior Citizen Identity Card/ Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/vlcer/certificate',
    description=""" API to verify Valuation Certificate. """,
    tags=['certificate_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def vlcer(body: VlcerCertificatePostRequest = None):
    """
    Valuation Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
